<a href="https://colab.research.google.com/github/sumana-vemuri/ADATA690-WANG/blob/master/assignments/pandas_aggregate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import string


In [3]:
x=range(5)
type(x)

range

In [4]:
list(x)

[0, 1, 2, 3, 4]

In [6]:
y=np.arange(5)
type(y)

numpy.ndarray

In [11]:
list(y)

[0, 1, 2, 3, 4]

In [14]:
#builder pattern 
a=np.arange(100)
print(a)
#one dimenstion 
a
#2D
b=a.reshape(10,10)
b
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [19]:
string.ascii_uppercase

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [13]:
x=np.arange(100).reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
y=list(string.ascii_uppercase)[0:10]
y

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [18]:
df=pd.DataFrame(x, columns=y)
df

A   B   C   D   E   F   G   H   I   J
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [26]:
df.dtypes
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       10 non-null     int64
 1   B       10 non-null     int64
 2   C       10 non-null     int64
 3   D       10 non-null     int64
 4   E       10 non-null     int64
 5   F       10 non-null     int64
 6   G       10 non-null     int64
 7   H       10 non-null     int64
 8   I       10 non-null     int64
 9   J       10 non-null     int64
dtypes: int64(10)
memory usage: 928.0 bytes


(10, 10)

In [20]:
#to produce summary statistics
df.describe()

A          B          C  ...          H          I          J
count  10.000000  10.000000  10.000000  ...  10.000000  10.000000  10.000000
mean   45.000000  46.000000  47.000000  ...  52.000000  53.000000  54.000000
std    30.276504  30.276504  30.276504  ...  30.276504  30.276504  30.276504
min     0.000000   1.000000   2.000000  ...   7.000000   8.000000   9.000000
25%    22.500000  23.500000  24.500000  ...  29.500000  30.500000  31.500000
50%    45.000000  46.000000  47.000000  ...  52.000000  53.000000  54.000000
75%    67.500000  68.500000  69.500000  ...  74.500000  75.500000  76.500000
max    90.000000  91.000000  92.000000  ...  97.000000  98.000000  99.000000

[8 rows x 10 columns]

In [27]:
#the summary statistics does not produce the sum od each column or row
#we use aggregate function 
#default-- aggregate of rows
df.aggregate("sum")

A    450
B    460
C    470
D    480
E    490
F    500
G    510
H    520
I    530
J    540
dtype: int64

In [28]:
df.agg("sum", axis="columns")

0     45
1    145
2    245
3    345
4    445
5    545
6    645
7    745
8    845
9    945
dtype: int64

In [29]:
df.agg(['sum','median','std'])

A           B           C  ...           H           I           J
sum     450.000000  460.000000  470.000000  ...  520.000000  530.000000  540.000000
median   45.000000   46.000000   47.000000  ...   52.000000   53.000000   54.000000
std      30.276504   30.276504   30.276504  ...   30.276504   30.276504   30.276504

[3 rows x 10 columns]

In [30]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[np.nan,np.nan,np.nan]],columns=["A","B","C"])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [31]:
df.describe()

A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [32]:
df.agg("min", axis="columns")

0    1.0
1    4.0
2    7.0
3    NaN
dtype: float64

In [34]:
x=np.random.randint(0,100,100).reshape(20,5)
x

array([[54, 28, 87,  8, 85],
       [26, 94, 43, 86, 83],
       [81, 11, 34, 87, 37],
       [12, 41,  1, 69, 75],
       [72, 68, 28, 69, 80],
       [39, 51, 54,  1, 90],
       [31, 76, 99, 66,  2],
       [82, 47, 67, 81, 58],
       [36,  0, 76, 70, 40],
       [ 3, 84, 29,  4, 87],
       [73, 36, 76, 50, 18],
       [32,  6, 79, 55, 13],
       [93, 95, 29, 97, 87],
       [40, 11, 23, 63,  4],
       [14, 95, 86,  0, 78],
       [34, 29, 39, 13, 83],
       [49, 83,  6, 56, 76],
       [ 7, 86, 72, 79, 68],
       [43, 77,  5, 96, 81],
       [42, 97, 96, 14, 83]])

In [35]:
y=string.ascii_uppercase
y

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [37]:
y=list(y)[0:5]
y

['A', 'B', 'C', 'D', 'E']

In [38]:
df = pd.DataFrame(x,columns=y)
df

A   B   C   D   E
0   54  28  87   8  85
1   26  94  43  86  83
2   81  11  34  87  37
3   12  41   1  69  75
4   72  68  28  69  80
5   39  51  54   1  90
6   31  76  99  66   2
7   82  47  67  81  58
8   36   0  76  70  40
9    3  84  29   4  87
10  73  36  76  50  18
11  32   6  79  55  13
12  93  95  29  97  87
13  40  11  23  63   4
14  14  95  86   0  78
15  34  29  39  13  83
16  49  83   6  56  76
17   7  86  72  79  68
18  43  77   5  96  81
19  42  97  96  14  83

In [40]:
df.describe()

A         B          C         D          E
count  20.000000  20.00000  20.000000  20.00000  20.000000
mean   43.150000  55.75000  51.450000  53.20000  61.400000
std    25.925551  33.63406  31.626896  33.74923  30.475875
min     3.000000   0.00000   1.000000   0.00000   2.000000
25%    29.750000  28.75000  28.750000  13.75000  39.250000
50%    39.500000  59.50000  48.500000  64.50000  77.000000
75%    58.500000  84.50000  76.750000  79.50000  83.000000
max    93.000000  97.00000  99.000000  97.00000  90.000000